#!/bin/bash
#Set job requirements
#SBATCH -N 1
#SBATCH -t 4:00

#iRODS + Python
module load 2019
module load Python
cd /home/<FILL IN>/iRODS-Compute-Tutorial-Words
# call the program
python wordsWorkflow.py > /home/<FILL IN>/iRODS-Compute-Tutorial-Words/outputjob
